"use client";

import { useEffect, useState } from "react";
import type { CSSProperties } from "react";
import styles from "../../files/files.module.css";

type ResearchItem = { status: string; meta: string; title: string; description: string; linkLabel: string; link: string };
type ExperienceItem = { dates: string; role: string; company: string; description: string };
type SiteSettings = { heroScale: number; headingScale: number; bodyScale: number; aboutEyebrowScale: number; aboutEyebrowTracking: number; researchTitleScale: number; experienceTitleScale: number; heroGreeting: string; heroDescription: string; aboutEyebrow: string; aboutHeadingPrimary: string; aboutHeadingAccent: string; aboutDescription: string; workLabel: string; workRange: string; workTag: string; workTitlePrimary: string; workTitleAccent: string; workDescription: string; workLinkLabel: string; researchLabel: string; researchHeadingPrimary: string; researchHeadingAccent: string; experienceLabel: string; educationLabel: string; educationHeadingPrimary: string; educationHeadingAccent: string; footerHeading: string };
type PortfolioContent = { research: ResearchItem[]; experience: ExperienceItem[]; settings: SiteSettings };
type ScaleField = "heroScale" | "headingScale" | "bodyScale" | "aboutEyebrowScale" | "researchTitleScale" | "experienceTitleScale";
type Target = { scope: "settings"; field: keyof SiteSettings; label: string; scale?: ScaleField; base?: number; min?: number; max?: number; tracking?: boolean } | { scope: "research"; index: number; field: keyof ResearchItem; label: string; scale?: ScaleField; base?: number; min?: number; max?: number } | { scope: "experience"; index: number; field: keyof ExperienceItem; label: string; scale?: ScaleField; base?: number; min?: number; max?: number };

const blankResearch: ResearchItem = { status: "Under review", meta: "Journal / year", title: "", description: "", linkLabel: "Read more", link: "" };
const blankExperience: ExperienceItem = { dates: "", role: "", company: "", description: "" };

function FullPortfolioPreview({ content, selected, onSelect }: { content: PortfolioContent; selected: Target; onSelect: (target: Target) => void }) {
  const s = content.settings;
  const typeStyle = { "--hero-scale": s.heroScale, "--heading-scale": s.headingScale, "--body-scale": s.bodyScale, "--about-eyebrow-scale": s.aboutEyebrowScale, "--about-eyebrow-tracking": s.aboutEyebrowTracking, "--research-title-scale": s.researchTitleScale, "--experience-title-scale": s.experienceTitleScale } as CSSProperties;
  function editable(target: Target, text: string, className = "") { let active = selected.scope === target.scope && selected.field === target.field; if (active && target.scope !== "settings" && selected.scope !== "settings") active = selected.index === target.index; return <button type="button" className={`${styles.editablePreview} ${active ? styles.editablePreviewActive : ""} ${className}`} onClick={() => onSelect(target)}>{text || "Click to add text"}</button>; }
  const setting = (field: keyof SiteSettings, label: string, scale?: ScaleField, base?: number, min?: number, max?: number, tracking?: boolean): Target => ({ scope: "settings", field, label, scale, base, min, max, tracking });
  const research = (index: number, field: keyof ResearchItem, label: string, scale?: ScaleField, base?: number, min?: number, max?: number): Target => ({ scope: "research", index, field, label, scale, base, min, max });
  const experience = (index: number, field: keyof ExperienceItem, label: string, scale?: ScaleField, base?: number, min?: number, max?: number): Target => ({ scope: "experience", index, field, label, scale, base, min, max });
  return <div className={styles.fullPreview}><main style={typeStyle}>
    <nav className="nav"><span className="brand">LA<span>R</span></span><div className="navLinks"><span>About</span><span>Portfolio</span><span>Research</span><span>Experience</span><span>Education</span></div><span className="contact">LinkedIn â†—</span></nav>
    <section className="hero"><div className="heroCopy"><div className="metrics"><span><b>3.67</b> GPA / 4.0</span><span><b>Top 3</b> Finance program</span></div><h1>{editable(setting("heroGreeting", "Hero greeting", "heroScale", 224, 180, 291), s.heroGreeting)}</h1>{editable(setting("heroDescription", "Hero description", "bodyScale", 16, 13, 21), s.heroDescription, "signature")}<div className="heroLinks"><span>Scroll down â†—</span><span>Let's work together â†—</span></div></div><div className="portrait"><div className="portraitFrame"><img src="/profile-cutout.png" alt="Le Quang Anh" /></div><p>Hanoi, Vietnam<br/>CFA Level II Candidate</p></div></section>
    <section className="intro"><p className="eyebrow aboutEyebrow">{editable(setting("aboutEyebrow", "About label", "aboutEyebrowScale", 12, 8, 18, true), s.aboutEyebrow)}</p><div><h2>{editable(setting("aboutHeadingPrimary", "About heading - first line", "headingScale", 96, 77, 125), s.aboutHeadingPrimary)}<em>{editable(setting("aboutHeadingAccent", "About heading - italic line", "headingScale", 96, 77, 125), s.aboutHeadingAccent)}</em></h2>{editable(setting("aboutDescription", "About description", "bodyScale", 16, 13, 21), s.aboutDescription)}</div></section>
    <section className="work"><div className="workHead"><p className="eyebrow">{editable(setting("workLabel", "Portfolio label", "aboutEyebrowScale", 12, 8, 18), s.workLabel)}</p>{editable(setting("workRange", "Portfolio range", "aboutEyebrowScale", 12, 8, 18), s.workRange)}</div><article className="feature"><div><p className="tag">{editable(setting("workTag", "Portfolio tag", "aboutEyebrowScale", 12, 8, 18), s.workTag)}</p><h2>{editable(setting("workTitlePrimary", "Portfolio title - first line", "headingScale", 96, 77, 125), s.workTitlePrimary)}{editable(setting("workTitleAccent", "Portfolio title - second line", "headingScale", 96, 77, 125), s.workTitleAccent)}</h2>{editable(setting("workDescription", "Portfolio description", "bodyScale", 16, 13, 21), s.workDescription)}{editable(setting("workLinkLabel", "Portfolio link text", "bodyScale", 16, 13, 21), s.workLinkLabel)}</div><div className="modelGrid"><span>FCFE</span><span>FCFF</span><span>J. P/E</span><span>J. P/B</span></div></article></section>
    <section className="research"><div className="researchHead"><p className="eyebrow">{editable(setting("researchLabel", "Research label", "aboutEyebrowScale", 12, 8, 18), s.researchLabel)}</p><h2>{editable(setting("researchHeadingPrimary", "Research heading - first line", "headingScale", 96, 77, 125), s.researchHeadingPrimary)}{editable(setting("researchHeadingAccent", "Research heading - second line", "headingScale", 96, 77, 125), s.researchHeadingAccent)}</h2></div><div className="researchList">{content.research.map((item, index) => <article key={`preview-research-${index}`}><span>{String(index + 1).padStart(2, "0")} - {editable(research(index, "status", `Research ${index + 1}: status`, "aboutEyebrowScale", 12, 8, 18), item.status)}</span><div><p className="researchMeta">{editable(research(index, "meta", `Research ${index + 1}: journal / year`, "aboutEyebrowScale", 12, 8, 18), item.meta)}</p><h3>{editable(research(index, "title", `Research ${index + 1}: title`, "researchTitleScale", 38, 25, 57), item.title)}</h3>{editable(research(index, "description", `Research ${index + 1}: description`, "bodyScale", 16, 13, 21), item.description)}{editable(research(index, "linkLabel", `Research ${index + 1}: link text`, "bodyScale", 16, 13, 21), item.linkLabel)}</div></article>)}</div></section>
    <section className="experience"><p className="eyebrow">{editable(setting("experienceLabel", "Experience label", "aboutEyebrowScale", 12, 8, 18), s.experienceLabel)}</p>{content.experience.map((item, index) => <article key={`preview-experience-${index}`}><p>{String(index + 1).padStart(2, "0")}</p><div><span>{editable(experience(index, "dates", `Experience ${index + 1}: dates`, "aboutEyebrowScale", 12, 8, 18), item.dates)}</span><h3>{editable(experience(index, "role", `Experience ${index + 1}: role`, "experienceTitleScale", 27, 18, 41), item.role)}</h3><b>{editable(experience(index, "company", `Experience ${index + 1}: company`, "bodyScale", 16, 13, 21), item.company)}</b></div>{editable(experience(index, "description", `Experience ${index + 1}: description`, "bodyScale", 16, 13, 21), item.description)}</article>)}</section>
    <section className="education"><div><p className="eyebrow">{editable(setting("educationLabel", "Education label", "aboutEyebrowScale", 12, 8, 18), s.educationLabel)}</p><h2>{editable(setting("educationHeadingPrimary", "Education heading - first line", "headingScale", 96, 77, 125), s.educationHeadingPrimary)}{editable(setting("educationHeadingAccent", "Education heading - second line", "headingScale", 96, 77, 125), s.educationHeadingAccent)}</h2></div><div className="credentials"><article><span>2025</span><h3>BBA, Finance</h3><p>VNU University of Economics &amp; Business<br/>GPA 3.67 / 4.0 - Top 3 of program</p></article><article><span>In progress</span><h3>CFA Level II Candidate</h3><p>Chartered Financial Analyst Program</p></article><article><span>Toolkit</span><h3>Financial research &amp; modelling</h3><p>DCF - Comparable companies - Excel - Python - Flask - Bloomberg</p></article></div></section>
    <footer><p>{editable(setting("footerHeading", "Footer quote", "headingScale", 96, 77, 125), s.footerHeading)}</p><span>quanganh.ibd@gmail.com â†—</span><div><span>Â© 2026 Le Quang Anh</span><span>quanganh.org</span></div></footer>
  </main></div>;
}

export default function ContentAdmin() {
  const [content, setContent] = useState<PortfolioContent | null>(null);
  const [message, setMessage] = useState("Loading content...");
  const [saving, setSaving] = useState(false);
  const [selected, setSelected] = useState<Target>({ scope: "settings", field: "heroGreeting", label: "Hero greeting", scale: "heroScale", base: 224, min: 180, max: 291 });

  useEffect(() => {
    fetch("/api/admin/content").then(async (response) => {
      if (response.status === 401) throw new Error("Sign in at File Admin first.");
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Could not load content.");
      return data;
    }).then((data) => { setContent(data); setMessage(""); }).catch((error: Error) => setMessage(error.message));
  }, []);

  function updateSettings(field: keyof SiteSettings, value: string | number) { if (content) setContent({ ...content, settings: { ...content.settings, [field]: value } }); }
  function updateResearch(index: number, field: keyof ResearchItem, value: string) { if (content) { const research = [...content.research]; research[index] = { ...research[index], [field]: value }; setContent({ ...content, research }); } }
  function updateExperience(index: number, field: keyof ExperienceItem, value: string) { if (content) { const experience = [...content.experience]; experience[index] = { ...experience[index], [field]: value }; setContent({ ...content, experience }); } }
  function valueOf(target: Target) { if (!content) return ""; if (target.scope === "settings") return String(content.settings[target.field]); if (target.scope === "research") return content.research[target.index]?.[target.field] || ""; return content.experience[target.index]?.[target.field] || ""; }
  function updateTarget(value: string) { if (selected.scope === "settings") updateSettings(selected.field, value); else if (selected.scope === "research") updateResearch(selected.index, selected.field, value); else updateExperience(selected.index, selected.field, value); }
  function setScale(value: number) { if (!content || !selected.scale || !selected.base) return; const min = selected.min ?? 10; const max = selected.max ?? 300; updateSettings(selected.scale, Math.max(min, Math.min(max, value)) / selected.base); }
  function scaleValue() { return content && selected.scale && selected.base ? Math.round(content.settings[selected.scale] * selected.base) : 0; }
  function move<T>(items: T[], index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= items.length) return items; const copy = [...items]; [copy[index], copy[target]] = [copy[target], copy[index]]; return copy; }
  async function save() { if (!content) return; setSaving(true); setMessage("Publishing..."); try { const response = await fetch("/api/admin/content", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(content) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not publish."); setContent(data); setMessage("Published. Your portfolio is updated."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not publish."); } finally { setSaving(false); } }
  function editable(target: Target, text: string, className = "") { let active = selected.scope === target.scope && selected.field === target.field; if (active && target.scope !== "settings" && selected.scope !== "settings") active = selected.index === target.index; return <button type="button" className={`${styles.editablePreview} ${active ? styles.editablePreviewActive : ""} ${className}`} onClick={() => setSelected(target)}>{text || "Click to add text"}</button>; }

  if (!content) return <main className={styles.page}><header className={styles.header}><a className={styles.brand} href="/">LA<sup>R</sup></a></header><p className={styles.status}>{message}</p></main>;
  const s = content.settings;
  return <main className={styles.page}>
    <header className={styles.header}><a className={styles.brand} href="/">LA<sup>R</sup></a><div className={styles.headerActions}><a className={styles.adminLink} href="/files/admin">File admin</a><a className={styles.adminLink} href="/">View portfolio</a></div></header>
    <section className={styles.adminIntro}><p className={styles.eyebrow}>Private area</p><h1>Visual editor.</h1><p>Click any text in the portfolio preview. Its content and typography controls will appear beside it, then Publish when you are ready.</p><button className={styles.publishButton} onClick={() => void save()} disabled={saving}>{saving ? "Publishing..." : "Publish changes"}</button>{message && <p className={styles.message}>{message}</p>}</section>
    <section className={styles.visualEditor}>
      <FullPortfolioPreview content={content} selected={selected} onSelect={setSelected} />
      <aside className={styles.inspector}><p className={styles.eyebrow}>Selected text</p><h2>{selected.label}</h2><label>Content{selected.field === "description" || selected.field === "footerHeading" ? <textarea value={valueOf(selected)} onChange={(event) => updateTarget(event.target.value)} /> : <input value={valueOf(selected)} onChange={(event) => updateTarget(event.target.value)} />}</label>{selected.scale && <div className={styles.inspectorControl}><span>Font size</span><div><button onClick={() => setScale(scaleValue() - 1)}>-</button><input type="number" value={scaleValue()} min={selected.min} max={selected.max} onChange={(event) => setScale(Number(event.target.value) || selected.min || 10)} /><em>px</em><button onClick={() => setScale(scaleValue() + 1)}>+</button></div></div>}{selected.scope === "settings" && selected.tracking && <label className={styles.inspectorTracking}>Letter spacing<input type="number" step="0.01" value={s.aboutEyebrowTracking} onChange={(event) => updateSettings("aboutEyebrowTracking", Math.max(0, Math.min(.25, Number(event.target.value) || 0)))} /><em>em</em></label>}<p className={styles.inspectorNote}>Changes appear in the full preview immediately. Font size is in pixels, like a document editor.</p></aside>
    </section>    <section className={styles.editorSection}><div className={styles.editorHead}><h2>Manage entries</h2><div><button onClick={() => setContent({ ...content, research: [...content.research, { ...blankResearch }] })}>Add research</button><button onClick={() => setContent({ ...content, experience: [...content.experience, { ...blankExperience }] })}>Add experience</button></div></div><p className={styles.settingsHint}>Add or remove items here, then click their text in the visual preview to edit it.</p>{content.research.map((item, index) => <article className={styles.editorCard} key={`research-${index}`}><div className={styles.editorCardHead}><span>Research {index + 1}</span><button className={styles.deleteButton} onClick={() => setContent({ ...content, research: content.research.filter((_, itemIndex) => itemIndex !== index) })}>Remove</button></div><div className={styles.editorGrid}><label>Status<input value={item.status} onChange={(event) => updateResearch(index, "status", event.target.value)} /></label><label>Journal / conference / year<input value={item.meta} onChange={(event) => updateResearch(index, "meta", event.target.value)} /></label></div><button onClick={() => setContent({ ...content, research: move(content.research, index, -1) })} disabled={index === 0}>Move up</button><button onClick={() => setContent({ ...content, research: move(content.research, index, 1) })} disabled={index === content.research.length - 1}>Move down</button></article>)}{content.experience.map((item, index) => <article className={styles.editorCard} key={`experience-${index}`}><div className={styles.editorCardHead}><span>Experience {index + 1}</span><button className={styles.deleteButton} onClick={() => setContent({ ...content, experience: content.experience.filter((_, itemIndex) => itemIndex !== index) })}>Remove</button></div><div className={styles.editorGrid}><label>Dates<input value={item.dates} onChange={(event) => updateExperience(index, "dates", event.target.value)} /></label><label>Company<input value={item.company} onChange={(event) => updateExperience(index, "company", event.target.value)} /></label></div><button onClick={() => setContent({ ...content, experience: move(content.experience, index, -1) })} disabled={index === 0}>Move up</button><button onClick={() => setContent({ ...content, experience: move(content.experience, index, 1) })} disabled={index === content.experience.length - 1}>Move down</button></article>)}</section>
  </main>;
}
