const Arrow = () => <span aria-hidden="true">?</span>;

export default function Home() {
  return <main>
    <nav className="nav" aria-label="Main navigation"><a className="brand" href="#top">LA<span>.</span></a><div className="nav-links"><a href="#experience">Experience</a><a href="#research">Research</a><a href="#education">Education</a></div><a className="nav-contact" href="mailto:quanganh.ibd@gmail.com">Let's connect <Arrow /></a></nav>
    <section className="hero" id="top"><div><p className="eyebrow">Finance · Research · Valuation</p><h1>Le Quang<br /><em>Anh.</em></h1><p className="lead">Finance &amp; Deals Analyst building investment insights from market data, policy shifts, and company fundamentals.</p><a className="button" href="mailto:quanganh.ibd@gmail.com">Get in touch <Arrow /></a></div><div className="photo"><span>Profile<br/>photo</span><small>Based in Hanoi, Vietnam · CFA Level II Candidate</small></div></section>
    <section className="facts"><div><b>3.67<small>/4.0</small></b><p>GPA · Top 3 of program</p></div><div><b>02<small>+</small></b><p>Investment research roles</p></div><div><b>01</b><p>Live valuation web app</p></div><div><b>2025</b><p>Finance BBA completion</p></div></section>
    <section className="section" id="experience"><p className="kicker">01 — Experience</p><div><h2>Rigorous analysis,<br/>clearly communicated.</h2><p className="intro">I combine bottom-up financial modelling with a macro-informed view of the market — translating complexity into decision-useful investment perspectives.</p></div></section>
    <section className="experience"><article><p className="date">Jan 2025 — Apr 2025</p><div><p className="role">Equity Research Analyst Intern</p><h3>DSC Securities Corporation</h3></div><p>Produced a full equity research report on KBC and IDC, assessing FDI inflows, China+1 dynamics, and Global Minimum Tax implications. Modelled revenue and earnings scenarios using lease-rate trends and macro assumptions.</p></article><article><p className="date">Jun 2024 — Aug 2024</p><div><p className="role">Research &amp; Investment Intern</p><h3>FPT Capital</h3></div><p>Authored Vietnam's 2025 investment outlook covering growth drivers, capital-market development and sector rotation. Analysed FUEFCV50 ETF structure, attribution, catalysts and risks.</p></article><article><p className="date">2022 — 2023</p><div><p className="role">Sales Associate</p><h3>Cat Hai Oil &amp; Grease</h3></div><p>Advised industrial and automotive customers on product selection, increasing average transaction value by 15% through consultative selling.</p></article></section>
    <section className="work" id="research"><p className="kicker">02 — Selected work</p><div className="projects"><article><p className="role">Independent project · Python / Flask</p><h2>Stock Valuation<br/>Web Application</h2><p>Equity valuation made practical. A full-stack tool that automates FCFE, FCFF, Justified P/E and Justified P/B models for listed stocks.</p><a href="https://valuation.quanganh.org" target="_blank" rel="noreferrer">Visit valuation.quanganh.org <Arrow /></a></article><article><span>MODELS</span><b>04</b><p>FCFE · FCFF<br/>Justified P/E · P/B</p></article><article><span>FOCUS</span><b>01</b><p>Input-driven<br/>equity valuation</p></article></div></section>
    <section className="section education" id="education"><p className="kicker">03 — Education &amp; credentials</p><div><h2>Foundation for<br/>the next chapter.</h2><p className="intro">Preparing for advanced study in finance while bringing an applied research and valuation foundation to each opportunity.</p><div className="credential"><article><p>2025</p><h3>BBA, Finance</h3><span>VNU University of Economics &amp; Business · Hanoi<br/>GPA 3.67 / 4.0 · Top 3 of program</span></article><article><p>In progress</p><h3>CFA Level II Candidate</h3><span>Chartered Financial Analyst Program</span></article><article><p>Additional</p><h3>Professional toolkit</h3><span>Securities Professional Certificate · Microsoft Office Specialist · IELTS Academic 6.5</span></article></div></div></section>
    <section className="skills"><p className="kicker">Core capabilities</p><div><span>DCF &amp; valuation</span><span>Financial modelling</span><span>Equity research</span><span>Macro analysis</span><span>Comparable companies</span><span>Python &amp; Flask</span></div></section>
    <footer><p>Open to finance opportunities and graduate study conversations.</p><a href="mailto:quanganh.ibd@gmail.com">quanganh.ibd@gmail.com <Arrow /></a><small>© {new Date().getFullYear()} Le Quang Anh · <a href="https://quanganh.org">quanganh.org</a></small></footer>
  </main>;
}

