const Arrow = () => <span aria-hidden="true">↗</span>;
export default function Home() { return <main>
<nav className="nav"><a className="brand" href="#top">LA<span>®</span></a><div className="navLinks"><a href="#about">About</a><a href="#work">Portfolio</a><a href="#experience">Experience</a><a href="#education">Education</a></div><a className="contact" href="mailto:quanganh.ibd@gmail.com">Contact <Arrow /></a></nav>
<section id="top" className="hero"><div className="heroCopy"><div className="metrics"><span><b>3.67</b> GPA / 4.0</span><span><b>Top 3</b> Finance program</span></div><h1>Hello<span>.</span></h1><p className="signature">I&apos;m <b>Le Quang Anh</b>, a finance &amp; deals analyst.</p><div className="heroLinks"><a href="#work">Scroll down <Arrow /></a><a href="mailto:quanganh.ibd@gmail.com">Let&apos;s work together <Arrow /></a></div></div><div className="portrait"><div className="portraitFrame"><span>your<br/>portrait</span></div><p>Hanoi, Vietnam<br/>CFA Level II Candidate</p></div></section>
<section className="intro" id="about"><p className="eyebrow">A finance-first perspective</p><div><h2>Market intelligence,<br/><em>made useful.</em></h2><p>I turn market data, policy shifts and company fundamentals into investment insight. My work brings research discipline, financial modelling and clear communication together.</p></div></section>
<section className="work" id="work"><div className="workHead"><p className="eyebrow">Selected portfolio</p><p>01 — 03</p></div><article className="feature"><div><p className="tag">Independent build · Python / Flask</p><h2>Stock valuation<br/>web application.</h2><p>Equity valuation made practical. A full-stack tool that automates FCFE, FCFF, Justified P/E and Justified P/B models for listed stocks.</p><a href="https://stock.quanganh.org" target="_blank" rel="noreferrer">Visit the live product <Arrow /></a></div><div className="modelGrid"><span>FCFE</span><span>FCFF</span><span>J. P/E</span><span>J. P/B</span></div></article></section>
<section className="experience" id="experience"><p className="eyebrow">Professional experience</p><article><p>01</p><div><span>Jan 2025 — Apr 2025</span><h3>Equity Research Analyst Intern</h3><b>DSC Securities Corporation</b></div><p>Produced a full equity-research report on KBC and IDC, covering FDI inflows, China+1 manufacturing dynamics, and Global Minimum Tax impacts. Modelled earnings scenarios using lease-rate trends and macro assumptions.</p></article><article><p>02</p><div><span>Jun 2024 — Aug 2024</span><h3>Research &amp; Investment Intern</h3><b>FPT Capital</b></div><p>Authored Vietnam&apos;s 2025 investment outlook and analysed the FUEFCV50 ETF&apos;s structure, index composition, performance attribution, catalysts and risks.</p></article><article><p>03</p><div><span>2022 — 2023</span><h3>Sales Associate</h3><b>Cat Hai Oil &amp; Grease</b></div><p>Advised industrial and automotive clients, increasing average transaction value by 15% through consultative selling.</p></article></section>
<section className="education" id="education"><div><p className="eyebrow">Education &amp; credentials</p><h2>A strong foundation<br/>for what&apos;s next.</h2></div><div className="credentials"><article><span>2025</span><h3>BBA, Finance</h3><p>VNU University of Economics &amp; Business<br/>GPA 3.67 / 4.0 · Top 3 of program</p></article><article><span>In progress</span><h3>CFA Level II Candidate</h3><p>Chartered Financial Analyst Program</p></article><article><span>Toolkit</span><h3>Financial research &amp; modelling</h3><p>DCF · Comparable companies · Excel · Python · Flask · Bloomberg</p></article></div></section>
<footer><p>Have an opportunity<br/>in mind?</p><a href="mailto:quanganh.ibd@gmail.com">quanganh.ibd@gmail.com <Arrow /></a><div><span>© {new Date().getFullYear()} Le Quang Anh</span><a href="https://quanganh.org" target="_blank" rel="noreferrer">quanganh.org</a></div></footer>
</main>; }


