"use client";

import type { CSSProperties, ReactNode } from "react";
import type { PortfolioContent, SiteSettings, ResearchItem, ExperienceItem } from "@/lib/portfolio-content";
import type { EditTarget, ScaleField } from "@/lib/portfolio-editor";

const Arrow = () => <span className="arrowIcon" aria-hidden="true" />;
type Props = { content: PortfolioContent; edit?: boolean; onSelect?: (target: EditTarget) => void };

export default function PortfolioPage({ content, edit = false, onSelect }: Props) {
  const s = content.settings;
  const style = { "--hero-scale": s.heroScale, "--heading-scale": s.headingScale, "--body-scale": s.bodyScale, "--about-eyebrow-scale": s.aboutEyebrowScale, "--about-eyebrow-tracking": s.aboutEyebrowTracking, "--research-title-scale": s.researchTitleScale, "--experience-title-scale": s.experienceTitleScale } as CSSProperties;
  const setting = (field: keyof SiteSettings, label: string, scale?: ScaleField, base?: number, min?: number, max?: number, tracking?: boolean): EditTarget => ({ scope: "settings", field, label, scale, base, min, max, tracking });
  const research = (index: number, field: keyof ResearchItem, label: string, scale?: ScaleField, base?: number, min?: number, max?: number): EditTarget => ({ scope: "research", index, field, label, scale, base, min, max });
  const experience = (index: number, field: keyof ExperienceItem, label: string, scale?: ScaleField, base?: number, min?: number, max?: number): EditTarget => ({ scope: "experience", index, field, label, scale, base, min, max });
  const text = (target: EditTarget, value: string): ReactNode => edit ? <span className="editorClickable" onClick={() => onSelect?.(target)}>{value || "Click to add text"}</span> : value;
  const link = (target: EditTarget, href: string, value: string) => edit ? <span className="editorPreviewLink">{text(target, value)} <Arrow /></span> : <a href={href} target="_blank" rel="noreferrer">{value || "Read more"} <Arrow /></a>;
  const footerText = edit ? text(setting("footerHeading", "Footer quote", "headingScale", 96, 77, 125), s.footerHeading) : s.footerHeading.split("\n").map((line, index) => <span key={`${line}-${index}`}>{line}{index < s.footerHeading.split("\n").length - 1 && <br/>}</span>);

  return <main className={edit ? "editorPreview" : ""} style={style}>
    <nav className="nav"><a className="brand" href="#top">LA<span>&reg;</span></a><div className="navLinks"><a href="#about">About</a><a href="#work">Portfolio</a><a href="#research">Research</a><a href="#experience">Experience</a><a href="#education">Education</a></div><a className="contact" href="https://www.linkedin.com/in/quanganhday/" target="_blank" rel="noreferrer">LinkedIn <Arrow /></a></nav>
    <section id="top" className="hero"><div className="heroCopy"><div className="metrics"><span><b>3.67</b> GPA / 4.0</span><span><b>Top 3</b> Finance program</span></div><h1 aria-label={s.heroGreeting}>{edit ? text(setting("heroGreeting", "Hero greeting", "heroScale", 224, 180, 291), s.heroGreeting) : [...s.heroGreeting].map((letter, index) => <span className={letter === "." ? "helloDot" : "helloLetter"} key={`${letter}-${index}`}>{letter}</span>)}</h1><p className="signature">{text(setting("heroDescription", "Hero description", "bodyScale", 16, 13, 21), s.heroDescription)}</p><div className="heroLinks"><a href="#work">Scroll down <Arrow /></a><a href="mailto:quanganh.ibd@gmail.com">Let&apos;s work together <Arrow /></a></div></div><div className="portrait"><div className="portraitFrame"><img src="/profile-cutout.png" alt="Le Quang Anh" /></div><p>Hanoi, Vietnam<br/>CFA Level II Candidate</p></div></section>
    <section className="intro" id="about"><p className="eyebrow aboutEyebrow">{text(setting("aboutEyebrow", "About label", "aboutEyebrowScale", 12, 8, 18, true), s.aboutEyebrow)}</p><div><h2>{text(setting("aboutHeadingPrimary", "About heading - first line", "headingScale", 96, 77, 125), s.aboutHeadingPrimary)}<br/><em>{text(setting("aboutHeadingAccent", "About heading - italic line", "headingScale", 96, 77, 125), s.aboutHeadingAccent)}</em></h2><p>{text(setting("aboutDescription", "About description", "bodyScale", 16, 13, 21), s.aboutDescription)}</p></div></section>
    <section className="work" id="work"><div className="workHead"><p className="eyebrow">{text(setting("workLabel", "Portfolio label", "aboutEyebrowScale", 12, 8, 18), s.workLabel)}</p><p>{text(setting("workRange", "Portfolio range", "aboutEyebrowScale", 12, 8, 18), s.workRange)}</p></div><article className="feature"><div><p className="tag">{text(setting("workTag", "Portfolio tag", "aboutEyebrowScale", 12, 8, 18), s.workTag)}</p><h2>{text(setting("workTitlePrimary", "Portfolio title - first line", "headingScale", 96, 77, 125), s.workTitlePrimary)}<br/>{text(setting("workTitleAccent", "Portfolio title - second line", "headingScale", 96, 77, 125), s.workTitleAccent)}</h2><p>{text(setting("workDescription", "Portfolio description", "bodyScale", 16, 13, 21), s.workDescription)}</p>{link(setting("workLinkLabel", "Portfolio link text and URL", "bodyScale", 16, 13, 21), s.workLink, s.workLinkLabel)}</div><div className="modelGrid"><span>FCFE</span><span>FCFF</span><span>J. P/E</span><span>J. P/B</span></div></article></section>
    <section className="research" id="research"><div className="researchHead"><p className="eyebrow">{text(setting("researchLabel", "Research label", "aboutEyebrowScale", 12, 8, 18), s.researchLabel)}</p><h2>{text(setting("researchHeadingPrimary", "Research heading - first line", "headingScale", 96, 77, 125), s.researchHeadingPrimary)}<br/>{text(setting("researchHeadingAccent", "Research heading - second line", "headingScale", 96, 77, 125), s.researchHeadingAccent)}</h2></div><div className="researchList">{content.research.map((item, index) => <article key={`${item.title}-${index}`}><span>{String(index + 1).padStart(2, "0")} &mdash; {text(research(index, "status", `Research ${index + 1}: status`, "aboutEyebrowScale", 12, 8, 18), item.status)}</span><div><p className="researchMeta">{text(research(index, "meta", `Research ${index + 1}: journal / year`, "aboutEyebrowScale", 12, 8, 18), item.meta)}</p><h3>{text(research(index, "title", `Research ${index + 1}: title`, "researchTitleScale", 38, 25, 57), item.title)}</h3><p>{text(research(index, "description", `Research ${index + 1}: description`, "bodyScale", 16, 13, 21), item.description)}</p>{item.link && link(research(index, "linkLabel", `Research ${index + 1}: link text and URL`, "bodyScale", 16, 13, 21), item.link, item.linkLabel)}</div></article>)}</div></section>
    <section className="experience" id="experience"><p className="eyebrow">{text(setting("experienceLabel", "Experience label", "aboutEyebrowScale", 12, 8, 18), s.experienceLabel)}</p>{content.experience.map((item, index) => <article key={`${item.role}-${index}`}><p>{String(index + 1).padStart(2, "0")}</p><div><span>{text(experience(index, "dates", `Experience ${index + 1}: dates`, "aboutEyebrowScale", 12, 8, 18), item.dates)}</span><h3>{text(experience(index, "role", `Experience ${index + 1}: role`, "experienceTitleScale", 27, 18, 41), item.role)}</h3><b>{text(experience(index, "company", `Experience ${index + 1}: company`, "bodyScale", 16, 13, 21), item.company)}</b></div><p>{text(experience(index, "description", `Experience ${index + 1}: description`, "bodyScale", 16, 13, 21), item.description)}</p></article>)}</section>
    <section className="education" id="education"><div><p className="eyebrow">{text(setting("educationLabel", "Education label", "aboutEyebrowScale", 12, 8, 18), s.educationLabel)}</p><h2>{text(setting("educationHeadingPrimary", "Education heading - first line", "headingScale", 96, 77, 125), s.educationHeadingPrimary)}<br/>{text(setting("educationHeadingAccent", "Education heading - second line", "headingScale", 96, 77, 125), s.educationHeadingAccent)}</h2></div><div className="credentials"><article><span>2025</span><h3>BBA, Finance</h3><p>VNU University of Economics &amp; Business<br/>GPA 3.67 / 4.0 &middot; Top 3 of program</p></article><article><span>In progress</span><h3>CFA Level II Candidate</h3><p>Chartered Financial Analyst Program</p></article><article><span>Toolkit</span><h3>Financial research &amp; modelling</h3><p>DCF &middot; Comparable companies &middot; Excel &middot; Python &middot; Flask &middot; Bloomberg</p></article></div></section>
    <footer><p>{footerText}</p><a href="mailto:quanganh.ibd@gmail.com">quanganh.ibd@gmail.com <Arrow /></a><div><span>&copy; {new Date().getFullYear()} Le Quang Anh</span><a href="https://quanganh.org" target="_blank" rel="noreferrer">quanganh.org</a></div></footer>
  </main>;
}
