"use client";

import { useEffect, useState } from "react";
import type { CSSProperties, ReactNode } from "react";
import type { CustomBlock, ExperienceItem, PortfolioContent, ResearchItem, SectionId, SiteSettings } from "@/lib/portfolio-content";
import { targetKey, type EditTarget, type ScaleField } from "@/lib/portfolio-editor";

const Arrow = () => <span className="arrowIcon" aria-hidden="true" />;
type Props = { content: PortfolioContent; edit?: boolean; selected?: EditTarget | null; onSelect?: (target: EditTarget) => void };

function EmailLink() {
  const [email, setEmail] = useState("");
  useEffect(() => setEmail(["quanganh.ibd", "gmail.com"].join("@")), []);
  return <a href={email ? `mailto:${email}` : "#"}>{email}{email && <> <Arrow /></>}</a>;
}

export default function PortfolioPage({ content, edit = false, selected, onSelect }: Props) {
  const s = content.settings;
  const style = { "--paper": s.paperColor || "#fcfcfa", "--ink": s.inkColor || "#132235", "--blue": !s.accentColor || s.accentColor === "#315be9" ? "#0f3d66" : s.accentColor, "--experience-bg": s.experienceColor || "#f3f6f8", "--hero-scale": s.heroScale, "--heading-scale": s.headingScale, "--body-scale": s.bodyScale, "--about-eyebrow-scale": s.aboutEyebrowScale, "--section-label-scale": s.sectionLabelScale, "--meta-scale": s.metaScale, "--about-eyebrow-tracking": s.aboutEyebrowTracking, "--research-title-scale": s.researchTitleScale, "--experience-title-scale": s.experienceTitleScale } as CSSProperties;
  const setting = (field: keyof SiteSettings, label: string, scale?: ScaleField, base?: number, min?: number, max?: number, tracking?: boolean): EditTarget => ({ scope: "settings", field, label, scale, base, min, max, tracking });
  const research = (index: number, field: keyof ResearchItem, label: string, scale?: ScaleField, base?: number, min?: number, max?: number): EditTarget => ({ scope: "research", index, field, label, scale, base, min, max });
  const experience = (index: number, field: keyof ExperienceItem, label: string, scale?: ScaleField, base?: number, min?: number, max?: number): EditTarget => ({ scope: "experience", index, field, label, scale, base, min, max });
  const custom = (index: number, field: keyof CustomBlock, label: string, scale?: ScaleField, base?: number, min?: number, max?: number): EditTarget => ({ scope: "custom", index, field, label, scale, base, min, max });
  const sectionStyle = (id: SectionId) => { const item = s.sectionStyles?.[id]; return { backgroundColor: item?.background || undefined, color: item?.color || undefined, fontWeight: item?.bold ? 700 : undefined } as CSSProperties; };
  const text = (target: EditTarget, value: string): ReactNode => {
    const active = selected?.scope === target.scope && selected.field === target.field && (target.scope === "settings" || selected?.scope === "settings" ? target.scope === selected?.scope : selected.index === target.index);
    const textStyle = s.textStyles?.[targetKey(target)];
    const inlineStyle = { fontWeight: textStyle?.bold ? 700 : undefined, color: textStyle?.color || undefined } as CSSProperties;
    if (edit) return <span style={inlineStyle} className={`editorClickable ${active ? "editorClickableActive" : ""}`} role="button" tabIndex={0} onClick={(event) => { event.stopPropagation(); onSelect?.(target); }} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onSelect?.(target); } }}>{value || "Click to add text"}</span>;
    const href = s.customLinks?.[targetKey(target)];
    return href ? <a style={inlineStyle} className="contentLink" href={href} target="_blank" rel="noreferrer">{value}</a> : <span style={inlineStyle}>{value}</span>;
  };
  const link = (target: EditTarget, href: string, value: string) => edit ? <span className="editorPreviewLink">{text(target, value)} <Arrow /></span> : <a href={href} target="_blank" rel="noreferrer">{value || "Read more"} <Arrow /></a>;
  const sectionClass = (base: string) => edit ? `${base} editorComponent` : base;
  const sectionClick = (target: EditTarget) => edit ? { onClick: () => onSelect?.(target) } : {};
  const footerText = edit ? text(setting("footerHeading", "Footer quote", "headingScale", 96, 36, 180), s.footerHeading) : s.footerHeading.split("\n").map((line, index) => <span key={`${line}-${index}`}>{line}{index < s.footerHeading.split("\n").length - 1 && <br/>}</span>);

  return <main className={edit ? "editorPreview portfolioPage" : "portfolioPage"} style={style}>
    <nav className="nav"><a className="brand" href="#top">LA<span>&reg;</span></a><div className="navLinks"><a href="#research">Research</a><a href="#work">Projects</a><a href="#about">About</a><a href="#experience">Experience</a><a href="#education">Education</a></div><a className="contact" href="https://www.linkedin.com/in/quanganhday/" target="_blank" rel="noreferrer">LinkedIn <Arrow /></a></nav>
    <section id="top" className={sectionClass("hero")} style={sectionStyle("hero")} {...sectionClick(setting("heroGreeting", "Hero component", "heroScale", 180, 60, 240))}><div className="heroCopy"><p className="heroKicker">Economics &amp; Finance Researcher</p><div className="metrics"><span><b>3.67</b> GPA / 4.0</span><span><b>Top 3</b> Finance program</span></div><h1 aria-label={s.heroGreeting}>{edit ? text(setting("heroGreeting", "Hero greeting", "heroScale", 180, 60, 240), s.heroGreeting) : [...s.heroGreeting].map((letter, index) => <span className={letter === "." ? "helloDot" : "helloLetter"} key={`${letter}-${index}`}>{letter}</span>)}</h1><p className="signature">{text(setting("heroDescription", "Hero description", "bodyScale", 16, 10, 48), s.heroDescription)}</p><p className="heroFocus">Empirical Banking &middot; Corporate Finance &middot; Development Economics</p><div className="heroLinks"><a href="#research">Selected research <Arrow /></a><a href="#contact">Let&apos;s work together <Arrow /></a></div></div><div className="portrait"><div className="portraitFrame"><img src="/profile-cutout.png" alt="Le Quang Anh" /></div><p>Hanoi, Vietnam<br/>CFA Level II Candidate</p></div></section>
    <section className={sectionClass("intro")} id="about" style={sectionStyle("about")} {...sectionClick(setting("aboutEyebrow", "About component", "aboutEyebrowScale", 12, 8, 36, true))}><p className="eyebrow aboutEyebrow">{text(setting("aboutEyebrow", "About label", "aboutEyebrowScale", 12, 8, 36, true), s.aboutEyebrow)}</p><div><h2>{text(setting("aboutHeadingPrimary", "About heading - first line", "headingScale", 96, 36, 180), s.aboutHeadingPrimary)}<br/><em>{text(setting("aboutHeadingAccent", "About heading - italic line", "headingScale", 96, 36, 180), s.aboutHeadingAccent)}</em></h2><p>{text(setting("aboutDescription", "About description", "bodyScale", 16, 10, 48), s.aboutDescription)}</p></div></section>
    <section className={sectionClass("work")} id="work" style={sectionStyle("work")} {...sectionClick(setting("workLabel", "Projects component", "sectionLabelScale", 12, 8, 36))}><div className="workHead"><p className="eyebrow">{text(setting("workLabel", "Projects label", "sectionLabelScale", 12, 8, 36), s.workLabel)}</p><p>{text(setting("workRange", "Projects range", "metaScale", 12, 8, 36), s.workRange)}</p></div><article className="feature"><div><p className="tag">{text(setting("workTag", "Projects tag", "metaScale", 12, 8, 36), s.workTag)}</p><h2>{text(setting("workTitlePrimary", "Projects title - first line", "headingScale", 96, 36, 180), s.workTitlePrimary)}<br/>{text(setting("workTitleAccent", "Projects title - second line", "headingScale", 96, 36, 180), s.workTitleAccent)}</h2><p>{text(setting("workDescription", "Projects description", "bodyScale", 16, 10, 48), s.workDescription)}</p>{link(setting("workLinkLabel", "Projects link text and URL", "bodyScale", 16, 10, 48), s.workLink, s.workLinkLabel)}</div><div className="modelGrid"><span>FCFE</span><span>FCFF</span><span>J. P/E</span><span>J. P/B</span></div></article></section>
    <section className={sectionClass("research")} id="research" style={sectionStyle("research")} {...sectionClick(setting("researchLabel", "Research component", "sectionLabelScale", 12, 8, 36))}><div className="researchHead"><p className="eyebrow">{text(setting("researchLabel", "Research label", "sectionLabelScale", 12, 8, 36), s.researchLabel)}</p><h2>{text(setting("researchHeadingPrimary", "Research heading - first line", "headingScale", 96, 36, 180), s.researchHeadingPrimary)}<br/>{text(setting("researchHeadingAccent", "Research heading - second line", "headingScale", 96, 36, 180), s.researchHeadingAccent)}</h2></div><div className="researchList">{content.research.map((item, index) => <article key={`${item.title}-${index}`}><span>{String(index + 1).padStart(2, "0")} &mdash; {text(research(index, "status", `Research ${index + 1}: status`, "metaScale", 12, 8, 36), item.status)}</span><div><p className="researchMeta">{text(research(index, "meta", `Research ${index + 1}: journal / year`, "metaScale", 12, 8, 36), item.meta)}</p><h3>{text(research(index, "title", `Research ${index + 1}: title`, "researchTitleScale", 38, 16, 72), item.title)}</h3><p>{text(research(index, "description", `Research ${index + 1}: description`, "bodyScale", 16, 10, 48), item.description)}</p>{item.link && link(research(index, "linkLabel", `Research ${index + 1}: link text and URL`, "bodyScale", 16, 10, 48), item.link, item.linkLabel)}</div></article>)}</div></section>
    <section className={sectionClass("experience")} id="experience" style={sectionStyle("experience")} {...sectionClick(setting("experienceLabel", "Experience component", "sectionLabelScale", 12, 8, 36))}><p className="eyebrow">{text(setting("experienceLabel", "Experience label", "sectionLabelScale", 12, 8, 36), s.experienceLabel)}</p>{content.experience.map((item, index) => <article key={`${item.role}-${index}`}><p>{String(index + 1).padStart(2, "0")}</p><div><span>{text(experience(index, "dates", `Experience ${index + 1}: dates`, "metaScale", 12, 8, 36), item.dates)}</span><h3>{text(experience(index, "role", `Experience ${index + 1}: role`, "experienceTitleScale", 27, 14, 60), item.role)}</h3><b>{text(experience(index, "company", `Experience ${index + 1}: company`, "bodyScale", 16, 10, 48), item.company)}</b></div><p>{text(experience(index, "description", `Experience ${index + 1}: description`, "bodyScale", 16, 10, 48), item.description)}</p></article>)}</section>
    <section className={sectionClass("education")} id="education" style={sectionStyle("education")} {...sectionClick(setting("educationLabel", "Education component", "sectionLabelScale", 12, 8, 36))}><div><p className="eyebrow">{text(setting("educationLabel", "Education label", "sectionLabelScale", 12, 8, 36), s.educationLabel)}</p><h2>{text(setting("educationHeadingPrimary", "Education heading - first line", "headingScale", 96, 36, 180), s.educationHeadingPrimary)}<br/>{text(setting("educationHeadingAccent", "Education heading - second line", "headingScale", 96, 36, 180), s.educationHeadingAccent)}</h2></div><div className="credentials"><article><span>2021 - 2025</span><h3>BBA, International Business &amp; Supply Chain Management</h3><p>University of St. Francis, joint program with VNU University of Economics &amp; Business<br/>Cum Laude &middot; GPA 3.67 / 4.0 &middot; Top 3 of program</p></article><article><span>In progress</span><h3>CFA Level II Candidate</h3><p>Level I Exam Passed</p></article><article><span>Methods &amp; data</span><h3>Empirical finance research</h3><p>Python &middot; Stata &middot; SQL &middot; LaTeX &middot; Panel data &middot; Financial statements</p></article></div></section>
    {content.customBlocks.map((block, index) => <section key={block.id} className={`${sectionClass("customBlock")} customBlock customBlock-${block.type}`} style={{ backgroundColor: block.background, color: block.color, fontWeight: block.bold ? 700 : undefined }} {...sectionClick(custom(index, "title", `Custom ${index + 1}: component`, "headingScale", 64, 24, 150))}><p className="eyebrow">{text(custom(index, "label", `Custom ${index +1}: label`, "sectionLabelScale", 12, 8, 36), block.label)}</p><h2>{text(custom(index, "title", `Custom ${index + 1}: title`, "headingScale", 64, 24, 150), block.title)}</h2><p>{text(custom(index, "body", `Custom ${index + 1}: text`, "bodyScale", 16, 10, 48), block.body)}</p>{block.link && link(custom(index, "linkLabel", `Custom ${index + 1}: link text and URL`, "bodyScale", 16, 10, 48), block.link, block.linkLabel)}</section>)}
    <footer id="contact" className={sectionClass("editorFooter")} style={sectionStyle("footer")} {...sectionClick(setting("footerHeading", "Footer component", "headingScale", 96, 36, 180))}><p>{footerText}</p><EmailLink /><div><span>&copy; {new Date().getFullYear()} Le Quang Anh</span><a href="https://quanganh.org" target="_blank" rel="noreferrer">quanganh.org</a></div></footer>
  </main>;
}
