"use client";

import { useEffect, useState } from "react";
import type { CSSProperties } from "react";
import type { ExperienceItem, PortfolioContent, ResearchItem, SiteSettings } from "@/lib/portfolio-content";

type ScaleField = "heroScale" | "headingScale" | "bodyScale" | "aboutEyebrowScale" | "researchTitleScale" | "experienceTitleScale";
type Target = { scope: "settings"; field: keyof SiteSettings; label: string; scale?: ScaleField; base?: number; min?: number; max?: number; tracking?: boolean } | { scope: "research"; index: number; field: keyof ResearchItem; label: string; scale?: ScaleField; base?: number; min?: number; max?: number } | { scope: "experience"; index: number; field: keyof ExperienceItem; label: string; scale?: ScaleField; base?: number; min?: number; max?: number };

export default function PortfolioPreview() {
  const [content, setContent] = useState<PortfolioContent | null>(null);
  useEffect(() => {
    function receive(event: MessageEvent) { if (event.origin === window.location.origin && event.data?.type === "portfolio-preview-content") setContent(event.data.content as PortfolioContent); }
    window.addEventListener("message", receive);
    window.parent.postMessage({ type: "portfolio-preview-ready" }, window.location.origin);
    return () => window.removeEventListener("message", receive);
  }, []);
  function select(target: Target) { window.parent.postMessage({ type: "portfolio-preview-select", target }, window.location.origin); }
  if (!content) return <main className="previewLoading">Loading portfolio preview...</main>;
  const s = content.settings;
  const typeStyle = { "--hero-scale": s.heroScale, "--heading-scale": s.headingScale, "--body-scale": s.bodyScale, "--about-eyebrow-scale": s.aboutEyebrowScale, "--about-eyebrow-tracking": s.aboutEyebrowTracking, "--research-title-scale": s.researchTitleScale, "--experience-title-scale": s.experienceTitleScale } as CSSProperties;
  const setting = (field: keyof SiteSettings, label: string, scale?: ScaleField, base?: number, min?: number, max?: number, tracking?: boolean): Target => ({ scope: "settings", field, label, scale, base, min, max, tracking });
  const research = (index: number, field: keyof ResearchItem, label: string, scale?: ScaleField, base?: number, min?: number, max?: number): Target => ({ scope: "research", index, field, label, scale, base, min, max });
  const experience = (index: number, field: keyof ExperienceItem, label: string, scale?: ScaleField, base?: number, min?: number, max?: number): Target => ({ scope: "experience", index, field, label, scale, base, min, max });
  const edit = (target: Target, text: string, className = "") => <span className={`editorClickable ${className}`} onClick={() => select(target)}>{text}</span>;
  return <main className="editorPreview" style={typeStyle}>
    <nav className="nav"><span className="brand">LA<span>®</span></span><div className="navLinks"><span>About</span><span>Portfolio</span><span>Research</span><span>Experience</span><span>Education</span></div><span className="contact">LinkedIn ↗</span></nav>
    <section className="hero"><div className="heroCopy"><div className="metrics"><span><b>3.67</b> GPA / 4.0</span><span><b>Top 3</b> Finance program</span></div><h1>{edit(setting("heroGreeting", "Hero greeting", "heroScale", 224, 180, 291), s.heroGreeting)}</h1><p className="signature">{edit(setting("heroDescription", "Hero description", "bodyScale", 16, 13, 21), s.heroDescription)}</p><div className="heroLinks"><span>Scroll down ↗</span><span>Let&apos;s work together ↗</span></div></div><div className="portrait"><div className="portraitFrame"><img src="/profile-cutout.png" alt="Le Quang Anh" /></div><p>Hanoi, Vietnam<br/>CFA Level II Candidate</p></div></section>
    <section className="intro"><p className="eyebrow aboutEyebrow">{edit(setting("aboutEyebrow", "About label", "aboutEyebrowScale", 12, 8, 18, true), s.aboutEyebrow)}</p><div><h2>{edit(setting("aboutHeadingPrimary", "About heading - first line", "headingScale", 96, 77, 125), s.aboutHeadingPrimary)}<br/><em>{edit(setting("aboutHeadingAccent", "About heading - italic line", "headingScale", 96, 77, 125), s.aboutHeadingAccent)}</em></h2><p>{edit(setting("aboutDescription", "About description", "bodyScale", 16, 13, 21), s.aboutDescription)}</p></div></section>
    <section className="work"><div className="workHead"><p className="eyebrow">{edit(setting("workLabel", "Portfolio label", "aboutEyebrowScale", 12, 8, 18), s.workLabel)}</p><p>{edit(setting("workRange", "Portfolio range", "aboutEyebrowScale", 12, 8, 18), s.workRange)}</p></div><article className="feature"><div><p className="tag">{edit(setting("workTag", "Portfolio tag", "aboutEyebrowScale", 12, 8, 18), s.workTag)}</p><h2>{edit(setting("workTitlePrimary", "Portfolio title - first line", "headingScale", 96, 77, 125), s.workTitlePrimary)}<br/>{edit(setting("workTitleAccent", "Portfolio title - second line", "headingScale", 96, 77, 125), s.workTitleAccent)}</h2><p>{edit(setting("workDescription", "Portfolio description", "bodyScale", 16, 13, 21), s.workDescription)}</p><span className="previewLink">{edit(setting("workLinkLabel", "Portfolio link text", "bodyScale", 16, 13, 21), s.workLinkLabel)} ↗</span></div><div className="modelGrid"><span>FCFE</span><span>FCFF</span><span>J. P/E</span><span>J. P/B</span></div></article></section>
    <section className="research"><div className="researchHead"><p className="eyebrow">{edit(setting("researchLabel", "Research label", "aboutEyebrowScale", 12, 8, 18), s.researchLabel)}</p><h2>{edit(setting("researchHeadingPrimary", "Research heading - first line", "headingScale", 96, 77, 125), s.researchHeadingPrimary)}<br/>{edit(setting("researchHeadingAccent", "Research heading - second line", "headingScale", 96, 77, 125), s.researchHeadingAccent)}</h2></div><div className="researchList">{content.research.map((item, index) => <article key={`${item.title}-${index}`}><span>{String(index + 1).padStart(2, "0")} - {edit(research(index, "status", `Research ${index + 1}: status`, "aboutEyebrowScale", 12, 8, 18), item.status)}</span><div><p className="researchMeta">{edit(research(index, "meta", `Research ${index + 1}: journal / year`, "aboutEyebrowScale", 12, 8, 18), item.meta)}</p><h3>{edit(research(index, "title", `Research ${index + 1}: title`, "researchTitleScale", 38, 25, 57), item.title)}</h3><p>{edit(research(index, "description", `Research ${index + 1}: description`, "bodyScale", 16, 13, 21), item.description)}</p><span className="previewLink">{edit(research(index, "linkLabel", `Research ${index + 1}: link text and URL`, "bodyScale", 16, 13, 21), item.linkLabel || "Read more")} ↗</span></div></article>)}</div></section>
    <section className="experience"><p className="eyebrow">{edit(setting("experienceLabel", "Experience label", "aboutEyebrowScale", 12, 8, 18), s.experienceLabel)}</p>{content.experience.map((item, index) => <article key={`${item.role}-${index}`}><p>{String(index + 1).padStart(2, "0")}</p><div><span>{edit(experience(index, "dates", `Experience ${index + 1}: dates`, "aboutEyebrowScale", 12, 8, 18), item.dates)}</span><h3>{edit(experience(index, "role", `Experience ${index + 1}: role`, "experienceTitleScale", 27, 18, 41), item.role)}</h3><b>{edit(experience(index, "company", `Experience ${index + 1}: company`, "bodyScale", 16, 13, 21), item.company)}</b></div><p>{edit(experience(index, "description", `Experience ${index + 1}: description`, "bodyScale", 16, 13, 21), item.description)}</p></article>)}</section>
    <section className="education"><div><p className="eyebrow">{edit(setting("educationLabel", "Education label", "aboutEyebrowScale", 12, 8, 18), s.educationLabel)}</p><h2>{edit(setting("educationHeadingPrimary", "Education heading - first line", "headingScale", 96, 77, 125), s.educationHeadingPrimary)}<br/>{edit(setting("educationHeadingAccent", "Education heading - second line", "headingScale", 96, 77, 125), s.educationHeadingAccent)}</h2></div><div className="credentials"><article><span>2025</span><h3>BBA, Finance</h3><p>VNU University of Economics &amp; Business<br/>GPA 3.67 / 4.0 - Top 3 of program</p></article><article><span>In progress</span><h3>CFA Level II Candidate</h3><p>Chartered Financial Analyst Program</p></article><article><span>Toolkit</span><h3>Financial research &amp; modelling</h3><p>DCF - Comparable companies - Excel - Python - Flask - Bloomberg</p></article></div></section>
    <footer><p>{edit(setting("footerHeading", "Footer quote", "headingScale", 96, 77, 125), s.footerHeading)}</p><span className="previewMail">quanganh.ibd@gmail.com ↗</span><div><span>© 2026 Le Quang Anh</span><span>quanganh.org</span></div></footer>
  </main>;
}
